main: net.minecore.mineplot.MinePlot
author: Numenorean95
authors: [tcoan98]
name: MinePlot
version: 1.0.0

commands:
    plot:
        description: Deals with buying and managing plots.
        usage: |
            /<command> list [world]
            /<command> price <x>:<z> <x>:<z>
            /<command> buy <x>:<z> <x>:<z> [name]
            /<command> <plot_name>
        permission: mp.plot
