main: net.minecore.mineplot.MinePlot
author: Numenorean95
authors: [tcoan98]
name: MinePlot
version: 1.2.2
load: POSTWORLD
depend: [MineCore]

commands:
    plot:
        description: Deals with buying and managing plots.
        usage: |
            /<command> list [world] - Lists all the plots you own (green) and you have rights to use (yellow)
            /<command> tool - Gets the tool for defining plots
            /<command> price - Gets the price of the currently selected plot
            /<command> price <x>:<z> <x>:<z> - Gets the price for the defined plot
            /<command> buy [name] - Buys the currently selected Plot, with the optional name
            /<command> buy <x>:<z> <x>:<z> [name] - Buys the plot defined by the coordinates
            /<command> <plot_name> - Gives standard info about the plot
            /<command> <plot_name> <add|remove> <player_name> - Adds or removes a player from this plot's allowed list
            /<command> <plot_name> allowed - Lists who is in the list of allowed players for the plot
            /<command> <plot_name> rename <new_name> - Renames your plot
            /<command> <plot_name> destroy - Removes the plot from your possesion with no reimbursement
        permission: mineplot.plot
    mineplot:
        description: Admin commands for MinePlot
        usage: |
            /<command> init <world> - Initializes the world as a Plotted world, so that players must buy plots to mine and build
        permission: mineplot.admin
        
permissions:
    mineplot.*:
        description: Gives access to all MinePlot commands
        children:
            mineplot.admin: true
            mineplot.plot: true
    mineplot.admin:
        description: Allows player to use MinePlot admin commands
        default: op
    mineplot.plot:
        description: Allows players to use all /plot commands
        default: true
    
 
